# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\">\n\x07Message\x12\r\n\x05title\x18\x01 \x01(\t\x12$\n\tsentences\x18\x02 \x03(\x0b\x32\x11.message.Sentence\"$\n\x08Sentence\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\tB*Z(github.com/no7wataru/proto-sqs-poc/protob\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_SENTENCE = DESCRIPTOR.message_types_by_name['Sentence']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Message)
  })
_sym_db.RegisterMessage(Message)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Sentence)
  })
_sym_db.RegisterMessage(Sentence)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/no7wataru/proto-sqs-poc/proto'
  _MESSAGE._serialized_start=26
  _MESSAGE._serialized_end=88
  _SENTENCE._serialized_start=90
  _SENTENCE._serialized_end=126
# @@protoc_insertion_point(module_scope)
